### PR TITLE
Development

### PR DESCRIPTION
**Pull request by deniscbrex**

### CODE REVIEW

**Review by AdnanAfsari — CHANGES_REQUESTED** [review]
Hello @DenisCuencaBrex .
Great Job.Just a small fix to make.

- there is no bored between nav items, add border exactly as the original one.

- put styles.css file into css folder, it will look more organized.

- update your readme with project descriptions, author name and live demo.
submit again for final review :)
Happy Coding

**Comment by deniscbrex** [comment]
Hi @AdnanAfsari! i fixed the nav bar, but when i add my styles.css in a folder my background-image just disappear what could be happening?
thank you!

**Comment by AdnanAfsari** [comment]
Hi @DenisCuencaBrex 
You have to work a little more.

- You added the nav item border but not like the original one.

-  create an img folder,put the styles.css file in there and   update index.html at line 7.
`<link rel="stylesheet" href="img/styles.css">`

- update your live demo with this link https://raw.githack.com/DenisCuencaBrex/Web-page-apple-clone/development/index.html

**Comment by deniscbrex** [comment]
Hi @AdnanAfsari 
 I changed the nav bar and added the css file in a folder, but my background image its dissapear, what could be happend?

**Comment by AdnanAfsari** [comment]
Hello @DenisCuencaBrex 
I appreciate your hard work but you still have to make few changes because i made a mistake in my last review that i mentioned img folder instead css, my bad, i am extremely sorry for that and wasting your time.

- please create a css folder and put your style.css in that folder. and make all the changes necessary.

- you can read this [post](https://stackoverflow.com/questions/15785390/css-images-in-another-folder) from StackOverflow to better understand why your background image does not show up after making the changes.

- Your navigation items are not in canter please check that and fix .

After making all the changes you can go ahead and merge your branch 👍 .you do not have to submit for another review,if you have any questions you can dm me in my slack.
and again i am extremely for my mistakes.

Happy Coding :)

**Pull request merged**
